### ISSUE TITLE
Activity is not getting updated on either of my Discord clients

### ISSUE THREAD

**Issue by Drakonas** [christopher-roelofs/GameEventHub#1]
![GameEventHub_2022-06-16_19-06-02](https://user-images.githubusercontent.com/438380/174192524-96c89893-9674-4925-b372-e62a2e14f0fc.png)
Perhaps I'm misunderstanding how this application works, but I have the Discord subscriber enabled, and I have the MiSTer publisher enabled.

The app detects game changes. Both my Discord clients have Game Activity enabled, but detect no games running at all. The Rich Presence activities don't seem to reach either of them. I run Discord and DiscordPTB for two separate accounts.

The documentation here states you should be sequentially pinging the entire range of 10 RPC ports to be sure it reaches known clients:

https://discord.com/developers/docs/topics/rpc#rpc-server-ports

Is this occurring? I'm trying to figure out if I did something wrong, or this is something wrong with the program.

I'm just trying to brainstorm. I'm out of ideas.

**Comment by christopher-roelofs** [comment]
Take a look at the readme for discord subscriber. This uses the rpc protocol used by the desktop app that needs to be running on the same machine as the script. This has only been tested on the official discord desktop app.

<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">For the Discord subcriber to work, you need to have the discord application install on the same machine the script is running on. This uses the RPC protocol.</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 600;">Setup an appication in Discord that will be used for this integration</strong></p><ul dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box;">Navigate to<span> </span><a href="https://discordapp.com/developers/" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; transition: color 80ms cubic-bezier(0.33, 1, 0.68, 1) 0s, background-color, box-shadow, border-color;">https://discordapp.com/developers/</a></li><li style="box-sizing: border-box; margin-top: 0.25em;">Click “Create an Application.”</li><li style="box-sizing: border-box; margin-top: 0.25em;">Setup the application how you want, name in MiSTer , and give it a good image.</li><li style="box-sizing: border-box; margin-top: 0.25em;">Right under the name of your application, locate your Client ID. You will need this later.</li><li style="box-sizing: border-box; margin-top: 0.25em;">Lastly, save your application.</li></ul><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Discord Config</p>

Config | Example | Details
-- | -- | --
application_id | 1234567890 | Discord application id
reconnect | true/false | reconnect to discord if failed to connect after initail retries

<div class="highlight highlight-source-json notranslate position-relative overflow-auto" style="box-sizing: border-box; position: relative !important; overflow: auto !important; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><pre style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; margin-top: 0px; margin-bottom: 0px; overflow-wrap: normal; padding: 16px; overflow: auto; line-height: 1.45; background-color: var(--color-canvas-subtle); border-radius: 6px; word-break: normal;">  <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"discord"</span>: {
        <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"application_id"</span>:<span class="pl-s" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);"><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span></span>,
        <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"reconnect"</span>:<span class="pl-c1" style="box-sizing: border-box; color: var(--color-prettylights-syntax-constant);">true</span>
    }</pre></div><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">In the pubsub.json file this requires an extra field for<span> </span><em style="box-sizing: border-box;">type</em><span> </span>because the library being use is async.</p><div class="highlight highlight-source-json notranslate position-relative overflow-auto" style="box-sizing: border-box; position: relative !important; overflow: auto !important; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><pre style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; margin-top: 0px; margin-bottom: 0px; overflow-wrap: normal; padding: 16px; overflow: auto; line-height: 1.45; background-color: var(--color-canvas-subtle); border-radius: 6px; word-break: normal;"><span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"Discord"</span>:{
   <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"status"</span>:<span class="pl-s" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);"><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span>enabled<span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span></span>,
   <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"type"</span>:<span class="pl-s" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);"><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span>async<span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span></span>,
   <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"subscribed_events"</span>:[]
}</pre></div><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Discord subscriber only has one action so it does not need to be defined. State and details are require, the rest can be left as "" if not wanted. The images are the names of the images uploaded in the developer portal. {tokens} can be used as the values to set them dynamically based on the event. The names will be set to lowercase automatically because discord makes the image names lowercase when uploading. Values for button links can't use {tokens} because discord does not seem to actually apply the change. It is best to use these for links that will not change like a twitch or youtube channel. You can max a max of 2 buttons and if no buttons are wanted remove the buttons field from the json object.</p><div class="highlight highlight-source-json notranslate position-relative overflow-auto" style="box-sizing: border-box; position: relative !important; overflow: auto !important; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><pre style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; margin-top: 0px; margin-bottom: 0px; overflow-wrap: normal; padding: 16px; overflow: auto; line-height: 1.45; background-color: var(--color-canvas-subtle); border-radius: 6px; word-break: normal;">{
   <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"description"</span>:<span class="pl-s" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);"><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span>Set the Discord status for the current game<span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span></span>,
   <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"status"</span>:<span class="pl-s" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);"><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span>enabled<span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span></span>,
   <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"state_text"</span>:<span class="pl-s" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);"><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span>{release_name}<span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span></span>,
   <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"details_text"</span>:<span class="pl-s" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);"><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span>{system}<span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span></span>,
   <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"small_text"</span>:<span class="pl-s" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);"><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span></span>,
   <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"small_image"</span>:<span class="pl-s" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);"><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span>misterkun<span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span></span>,
   <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"large_text"</span>:<span class="pl-s" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);"><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span></span>,
   <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"large_image"</span>:<span class="pl-s" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);"><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span>{core}<span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span></span>,
   <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"buttons"</span>:[
      {
         <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"label"</span>:<span class="pl-s" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);"><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span>Button 1<span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span></span>,
         <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"url"</span>:<span class="pl-s" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);"><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span>https://www.google.com<span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span></span>
      },
      {
         <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"label"</span>:<span class="pl-s" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);"><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span>Button 2<span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span></span>,
         <span class="pl-ent" style="box-sizing: border-box; color: var(--color-prettylights-syntax-entity-tag);">"url"</span>:<span class="pl-s" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);"><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span>https://www.google.com<span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span></span>
      }
   ]
}</pre></div>
</body>
</html>

**Comment by Drakonas** [comment]
So I had read all of that, and the part I was missing was that I had to actually configure the JSON with events and actions myself for it to do anything. I misunderstood this. The section for how to do it was far above the Discord and MiSTer sections, so I didn't think it was related to my interests.

Apologies. Maybe mentioning these steps in the setup section (after the developer portal stuff) would be a good idea?

1. Enable at least one subscriber and one publisher in pubsub.json.
2. Add events in the pubsub.json for the subscriber(s), and any number of actions you wish to have trigger when the event fires. See the "Publisher/Subscriber Model" section for details, referring to the events in each publisher section and actions listed in each subscriber section for how to configure. You can have one action per event, but list the same event multiple times.
3. If using the Discord subscriber, make sure to upload any wanted images to the Developer portal under the "Rich Presence" assets section, and name them to match what is in your actions. If it is a dynamic item, like {core} for example, keep in mind the image names cannot have spaces. The {core} names from the MiSTer should not have spaces, so this works for them. (naming the images atarilynx or gba2p, for example) Letter case does not matter.
4. Run the application while Discord is running on the same machine. DiscordPTB and Nightly are not supported. It should automatically connect to Discord, and start listening for the enabled publisher(s).

**Comment by christopher-roelofs** [comment]
Thanks for the feedback. I've added your steps to the readme.
